spring.application.name=proyecto1D

spring.datasource.url=jdbc:mysql://localhost:3306/base1d?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
